trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: MSBuild@1
  inputs:
    solution: '8GadgetPackIconChanger.sln'
    platform: 'Win32'
    configuration: 'Release'
    msbuildArguments: '/m'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\s\Release\'
    artifact: '8GadgetPackIconChanger Release directory'
    publishLocation: 'pipeline'
  displayName: 'Publish Pipeline Artifacts'