name: C++ MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: warrenbucley/Setup-MSBuild@v1
    - name: Build
      run: msbuild -m -p:Configuration=Release
